server.port: 8000

spring:
  application.name: message-service

  datasource:
    url: jdbc:postgresql://localhost:5432/rtc?currentSchema=rtc-messages
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
