spring:
  application.name: message-service

  datasource:
    url: jdbc:postgresql://localhost:5432/messages
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
